project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
]

project/e2c/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('upload/', include("file_upload.urls")),
                  path('', include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/file_upload/urls.py
from django.urls import path
from . import views

# namespace
app_name = "file_upload"
urlpatterns = [
    path('del/<int:id>', views.delete_file, name='delete'),
    # View File List
    path('list/', views.file_list, name='file_list'),
    # Upload Files Using Model Form
    path('', views.model_form_upload, name='model_form_upload'),
]

project/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

project/file_upload/models.py
from django.db import models
import os
from django.conf import settings
from django.core.exceptions import ValidationError

# Create your models here.
# Define user directory path


def file_size(value):
    limit = 524000
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 500KiB.')


def user_directory_path(instance, filename):
    return os.path.join("", filename)


class File(models.Model):
    file = models.FileField(upload_to='', null=True, validators=[file_size])

project/file_upload/forms.py
from django import forms
from .models import File
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3


# Model form
class FileUploadModelForm(forms.ModelForm):
    class Meta:
        model = File
        labels = {
            'file': ''
        }
        fields = ['file']
        widgets = {
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'})
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext != "xls":
            raise forms.ValidationError(".xls以外の拡張子ファイルはアップロードいただけません。")
        # return cleaned data is very important.
        return file

    captcha = ReCaptchaField(
        label='',
        widget=ReCaptchaV3(
            attrs={'required_score': 0.7}
        )
    )

project/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Post
import markdown


# Create your views here.

def paginate_queryset(request, queryset, count):
    """Pageオブジェクトを返す。

    ページングしたい場合に利用してください。

    countは、1ページに表示する件数です。
    返却するPgaeオブジェクトは、以下のような感じで使えます。

        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

    また、page_obj.object_list で、count件数分の絞り込まれたquerysetが取得できます。

    """
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


def index(request):
    post = Post.objects.all().order_by('-created_time')
    page_obj = paginate_queryset(request, post, 6)
    return render(request, 'blog/index.html', {
        'title': 'Excel -> CSV直行便',
        'post': page_obj.object_list,
        'page_obj': page_obj,
    })


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    return render(request, 'blog/detail.html', {
        'post': post,
        'title': post.title
    })

project/file_upload/views.py
from django.shortcuts import render, redirect
from .forms import FileUploadModelForm
from .models import File
from e2c import s3_method
from converter import excel2csv


# Create your views here.

# Upload File with ModelForm
def model_form_upload(request):
    if request.method == "POST":
        form = FileUploadModelForm(request.POST,
                                   request.FILES)
        if form.is_valid():
            f = form.save()
            key = "media/" + f.file.name
            print(key)
            bucket_name = s3_method.AWS_STORAGE_BUCKET_NAME
            xls_buffer = s3_method.receive_xls_from_bucket(bucket_name, key)
            xls_converter = excel2csv.Converter(xls_buffer, bucket_name)
            zipped_csv_buffer = xls_converter.pack_csv_files()
            key = key.rstrip('.xls') + '.zip'
            zip_response = s3_method.upload_zip_to_bucket(bucket_name, zipped_csv_buffer, key)
            return redirect("/upload/list/")
    else:
        form = FileUploadModelForm()
    return render(request, 'file_upload/index.html',
                  {'form': form, 'title': 'Excelファイルをアップロード'})


# Show file list
def file_list(request):
    files = File.objects.all().order_by("-id")
    zip_names, zip_urls, zip_sizes = [], [], []
    bucket_name = s3_method.AWS_STORAGE_BUCKET_NAME
    for file in files:
        zip_name = file.file.name.rstrip(".xls") + ".zip"
        zip_names.append(zip_name)

        zip_key = "media/" + zip_name
        zip_url = file.file.url.rstrip(".xls") + ".zip"
        zip_urls.append(zip_url)

        zip_size = s3_method.return_size_of_obj(bucket_name, zip_key)
        zip_sizes.append(zip_size)
    lst = zip(zip_names, zip_urls, zip_sizes, files)
    return render(request, 'file_upload/list.html',
                  {
                      'lst': lst,
                      'title': 'ファイルリスト'
                  })


def delete_file(request, id):
    file_id = id
    delete_files = File.objects.filter(id=file_id)
    for file in delete_files:
        xls_key = "media/" + file.file.name
        zip_key = ("media/" + file.file.name).rstrip(".xls") + ".zip"
        bucket_name = s3_method.AWS_STORAGE_BUCKET_NAME
        xls_del_response = s3_method.delete_obj_from_bucket(bucket_name, xls_key)
        zip_del_response = s3_method.delete_obj_from_bucket(bucket_name, zip_key)
    File.objects.filter(id=file_id).delete()
    return file_list(request)

project/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- GitHub Markdown CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@3.0.1/github-markdown.min.css">

    <style>
    /* Move down content because we have a fixed navbar that is 3.5rem tall */
    body {
      padding-top: 3.5rem;
    }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="navbar-brand"></div>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">ホーム<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/upload/list">ファイル</a>
            </li>
        </ul>
    </div>
</nav>

{% block main %}
{% endblock main %}

<footer class="container">
    <p>&copy; IWAI, 長野大学企業情報学部前川ゼミ, 2018-2025. This site is under the MIT license.
        <br>統計データは著作権法上認められている範囲内で引用されます.</p>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

</html>

project/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}

<main role="main" class="flex-shrink-0">
    <div class="jumbotron">
        <div class="container">
            <h1 class="mt-5">{{ post.title }}</h1>
            <p class="lead">
                <time class="entry-date" datetime="{{ post.created_time }}">
                    {{ post.created_time }}
                </time>
                by {{ post.author }}
            </p>
        </div>
    </div>

    <div class="container markdown-body">
        <p class="lead">{{ post.body|safe }}</p>
    </div>

    <div class="container pt-5 pb-1">
        <p class="lead"><a class="btn btn-secondary" href="/" role="button">戻る</a></p>
    </div>

    <hr>

</main>

{% endblock main %}

project/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
<main role='main'>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">{{ title }}</h1>
            <p>前川ゼミが参与している「信州デジタルコモンズプロジェクト／オープンデータプロジェクト」は、<br>
                「地域の諸データのオープンデータ化」という課題の解決を目指しています。<br>
                Excelの統計データを直接、データベース化するには難しいですが、CSVに変換したらそれほど難しくはありません。<br>
                このアプリを使ってExcelをCSVファイルに自動変換することで、<br>
                少しでもオープンデータ化においての「はじめてのハードル」を取り除きたいと思います。<br>
                精度・アルゴリズム等の問題点が未だ残っていますが、是非一度お試しください。
            </p>
            <p><a class="btn btn-primary btn-lg" href="/upload/" role="button">変換してみる</a></p>
        </div>
    </div>

    <div class="container">
        <div class="row mx-auto">
            {% for p in post %}
            <div class="col-md-4">
                <h2>{{ p.title }}</h2>
                <p>{{ p.excerpt }}</p>
                <p><a class="btn btn-secondary" href={{ p.get_absolute_url }} role="button">詳細</a></p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="container py-1">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <!-- 前へ の部分 -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- 数字の部分 -->
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="#!">{{ num }}</a>
                </li>
                    {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                    {% endif %}
                {% endfor %}

                <!-- 次へ の部分 -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <div class="container">
        <hr>
    </div>
</main>

{% endblock main %}

project/templates/file_upload/index.html
{% extends 'base.html' %}

{% block main %}
<main role="main" class="flex-shrink-0">
    <div class="jumbotron">
        <div class="container">
            <h1 class="mt-5">{{ title }}</h1>
            アップロード制限：ファイル拡張子が.xls・サイズが500KiB以下
        </div>
    </div>

    <div class="container">
        <p class="lead">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-info form-control" type="submit" value="submit">変換</button>
        </form>
        </p>
    </div>

    <div class="container pt-5 pb-1">
        <p class="lead"><a class="btn btn-secondary" href="/" role="button">戻る</a></p>
    </div>

    <hr>
</main>

{% endblock main %}

project/templates/file_upload/list.html
{% extends "base.html" %}

{% block main %}
<main role="main" class="flex-shrink-0">
    <div class="jumbotron">
        <div class="container">
            <h1 class="mt-5">ファイルリスト</h1>
        </div>
    </div>

    <div class="container">
        {% if lst %}
        <table class="table table-striped">
            <tbody>
            <tr>
                <td>出力ファイル</td>
                <td>元ファイル</td>
                <td>出力ファイルサイズ</td>
                <td>元ファイルサイズ</td>
                {% if perms.file_upload.delete_File %}
                <td>削除</td>
                {% endif %}
            </tr>
            {% for zip_name, zip_url, zip_size, file in lst %}
            <tr>
                <td><a href="{{ zip_url }}">{{ zip_name }}</a></td>
                <td><a href="{{ file.file.url }}">{{ file.file.name}}</a></td>
                <td>{{ zip_size | filesizeformat }}</td>
                <td>{{ file.file.size | filesizeformat }}</td>
                {% if perms.file_upload.delete_File %}
                <td>
                    <a class="btn btn-outline-danger btn-sm" href="{% url 'file_upload:delete' file.id %}"
                       role="button">削除</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="lead">
            まだ何もアップロードしていません。<br>
            <a href="/upload/">こちら</a>をクリックして変換したいExcelファイルをアップロードしてください。
            {% endif %}
        </p>
    </div>

    <div class="container">
        <p class="lead"><a class="btn btn-secondary" href="/" role="button">戻る</a></p>
    </div>

    <hr>
</main>
{% endblock %}